<?php
/*
 * Copyright 2021 LABOR.digital
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Last modified: 2021.07.14 at 12:34
 */

declare(strict_types=1);


namespace LaborDigital\T3ba\Tool\Tca\Preview;


interface PreviewLinkGeneratorInterface
{
    /**
     * Allows you to generate the basic link for a record preview. The Preview argument will be added automatically.
     *
     * @param   string  $tableName      The name of the database table to generate the preview for
     * @param   string  $uid            The unique id of the record to build the preview link for
     * @param   array   $configuration  The configuration array generated by the TcaTable enablePreviewLink method.
     * @param   array   $typoParams     The parameters generated by the TYPO3 core, for completeness.
     *
     * @return string
     */
    public function generate(string $tableName, string $uid, array $configuration, array $typoParams): string;
}
