<?php
/*
 * Copyright 2021 LABOR.digital
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Last modified: 2021.06.27 at 16:27
 */

declare(strict_types=1);


namespace LaborDigital\T3ba\ExtConfigHandler\FieldPreset;


use LaborDigital\T3ba\Core\Di\NoDiInterface;
use LaborDigital\T3ba\Core\VarFs\Mount;
use LaborDigital\T3ba\Tool\OddsAndEnds\ReflectionUtil;
use LaborDigital\T3ba\Tool\Tca\Builder\Logic\AbstractField;
use ReflectionMethod;

class AutocompleteGenerator implements NoDiInterface
{
    
    /**
     * @var \LaborDigital\T3ba\Core\VarFs\Mount
     */
    protected $fs;
    
    /**
     * FieldPresetAutocompleteGenerator constructor.
     *
     * @param   \LaborDigital\T3ba\Core\VarFs\Mount  $fsMount
     */
    public function __construct(Mount $fsMount)
    {
        $this->fs = $fsMount;
    }
    
    /**
     * Receives a list of presets generated by FieldPresetListGenerator and generates a
     * autocomplete helper interface into the var fs directory.
     *
     * This is a convenience feature for dev purposes only!
     *
     * @param   array  $presets
     */
    public function generate(array $presets): void
    {
        $methods = [];
        foreach ($presets as $key => $def) {
            $methods[] = $this->makePresetSrc($key, new ReflectionMethod($def[0], $def[1]));
        }
        
        $source = $this->makeInterfaceSrc($methods);
        
        $this->fs->setFileContent('/AutocompleteHelper/FieldPresetAutocompleteHelper.php', $source);
    }
    
    /**
     * Builds the source code for a single preset method
     *
     * @param   string             $key
     * @param   \ReflectionMethod  $method
     *
     * @return string
     */
    protected function makePresetSrc(string $key, ReflectionMethod $method): string
    {
        $comment = ReflectionUtil::sanitizeDesc((string)$method->getDocComment());
        $comment = array_map(static function ($line) { return '	 * ' . $line; }, $comment);
        
        return '
	/**
' . implode(PHP_EOL, $comment) . '
	 * @return \\' . AbstractField::class . '
	 *
	 * @see \\' . $method->getDeclaringClass()->getName() . '::' . $method->getName() . '();
	 */
	public function ' . $key
               . '(' . ReflectionUtil::generateMethodArgs($method) . '): \\'
               . AbstractField::class . ';
';
    }
    
    /**
     * Builds the outer source of the generated interface
     *
     * @param   array  $methods
     *
     * @return string
     */
    protected function makeInterfaceSrc(array $methods): string
    {
        return '<?php
declare(strict_types=1);

namespace LaborDigital\T3ba\Tool\Tca\Builder;

/**
 * ATTENTION: This is a autocomplete helper! It will only be generated in a development environment!
 * It is also not autoloadable and therefore not considered part of the active code-base!
 * DON\'T USE THIS IN YOUR CODE!
 *
 * IF YOU TELL ME YOUR CODE BROKE, BECAUSE YOU USED IT SOMEWHERE - I\'M GONNA LAUGH AT YOU!
 */
interface FieldPresetAutocompleteHelper {

' . implode(PHP_EOL . PHP_EOL, $methods) . '

}
';
    }
}
