name: Create new Release

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
    paths-ignore:
      - 'composer.json'
      - 'package.json'
      - 'CHANGELOG.md'
jobs:
  test:
    name: all tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ '7.3', '7.4' ]
        minMax: [ 'composerInstallMin', 'composerInstallMax' ]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      
      -
        name: Preparation
        run: chmod +x Build/Scripts/runTests.sh
      
      -
        name: Composer
        run: Build/Scripts/runTests.sh -p ${{ matrix.php }} -s ${{ matrix.minMax }}
      
      -
        name: Composer validate
        run: Build/Scripts/runTests.sh -p ${{ matrix.php }} -s composerValidate
      
      -
        name: Unit tests
        run: Build/Scripts/runTests.sh -p ${{ matrix.php }} -s unit
        #
        #            - name: Functional tests with mariadb
        #              run: Build/Scripts/runTests.sh -p ${{ matrix.php }} -d mariadb -s functional
        #
        #            - name: Functional tests with mssql
        #              run: Build/Scripts/runTests.sh -p ${{ matrix.php }} -d mssql -s functional
        #
        #            - name: Functional tests with postgres
        #              run: Build/Scripts/runTests.sh -p ${{ matrix.php }} -d postgres -s functional
        #
        #            - name: Functional tests with sqlite
        #              run: Build/Scripts/runTests.sh -p ${{ matrix.php }} -d sqlite -s functional
  documentation:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: test
    steps:
      -
        uses: actions/checkout@v1
      -
        name: vuepress-deploy
        uses: jenkey2011/vuepress-deploy@master
        env:
          CNAME: typo3-better-api.labor.tools
          ACCESS_TOKEN: ${{ secrets.ACTIONS_DEPLOY_TOKEN }}
          TARGET_BRANCH: gh-pages
          BUILD_SCRIPT: cd docs && npm i && npm run build
          BUILD_DIR: .vuepress/dist/
  release:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: test
    steps:
      -
        uses: actions/checkout@v1
      -
        name: Create Changelog and bump release version
        uses: labor-digital/conventional-release-action@master
        with:
          github-token: ${{ secrets.github_token }}
